version: '3.5'

networks:
  monitoring:
  nginx:
    name: nginx
  internal-nginx:
    external:
      name: internal-nginx

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    networks:
      - nginx
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root1234

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 127.0.0.1:80:80
    networks:
      - nginx
      - internal-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
volumes:
  logs:

