version: '3.5'

networks:
  monitoring:
  nginx:
    name: nginx
  internal-nginx:
    external:
      name: internal-nginx

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    networks:
      - nginx
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root1234

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx
      - internal-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/ssl:/etc/ssl:ro
      - ./aubry-front:/aubry-front
      - ./work:/work
      - ./cdn:/cdn
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"

  portainer:
    image: portainer/portainer-ce:alpine
    restart: always
    networks:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .data/portainer:/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        
volumes:
  logs:

