version: '3.5'

networks:
  monitoring:
  nginx:
    name: nginx

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    networks:
      - nginx
    volumes:
      - ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
volumes:
  logs:

