version: '3.5'

networks:
  monitoring:
  nginx:
    name: nginx
  internal-nginx:
    external:
      name: internal-nginx

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 127.0.0.1:80:80
    networks:
      - nginx
      - internal-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./technology:/technology
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
volumes:
  logs:

